### ISSUE TITLE
I can't open.

### ISSUE THREAD

**Issue by Funky7Monkey** [derbymutt/NetNone#2]
Everything is broken.

**Comment by derbymutt** [comment]
Can you start it from a command line and see if its throwing any exceptions?

Its working fine on Windows 8.1 with Java 1.8.

**Comment by Funky7Monkey** [comment]
It throws a splash screen and dies on Linux Mint.

**Comment by derbymutt** [comment]
Doe

**Comment by derbymutt** [comment]
Try 1.5_6, this issue may have been fixed.
I added a TryCatch for obtaining the user's home path.

If it does not crash out you may need to fix your linux build. 
http://stackoverflow.com/questions/1503284/java-system-getpropertyuser-home-returns this may be helpful in fixing that issue.

**Comment by derbymutt** [comment]
This appears to be an issue with your linux distro, and not related to this code.

Make sure you have Java 8 installed, and not an older version like Java 6 or 7.

Java Runtime Environment 8 http://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html
Java Development Kit 8 http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html
